CREATE TABLE IF NOT EXISTS ACT_HI_AGENT_SUBPROCESS (
    ID_                      VARCHAR(64)   NOT NULL,
    PROC_INST_ID_            VARCHAR(64)   NOT NULL,
    EXECUTION_ID_            VARCHAR(64)   NOT NULL,
    PROC_DEF_KEY_            VARCHAR(255),
    ELEMENT_ID_              VARCHAR(255),
    PROVIDER_                VARCHAR(64),
    MODEL_                   VARCHAR(255),
    GOAL_                    CLOB,
    INPUT_VARIABLES_         CLOB,
    START_TIME_              TIMESTAMP     NOT NULL,
    END_TIME_                TIMESTAMP,
    FINAL_OUTPUT_            CLOB,
    ITERATION_COUNT_         INT           NOT NULL DEFAULT 0,
    TOTAL_PROMPT_TOKENS_     BIGINT        NOT NULL DEFAULT 0,
    TOTAL_COMPLETION_TOKENS_ BIGINT        NOT NULL DEFAULT 0,
    REMOVAL_TIME_            TIMESTAMP,
    PRIMARY KEY (ID_)
);

CREATE INDEX IF NOT EXISTS IDX_HI_AGENT_SUB_PROC_INST ON ACT_HI_AGENT_SUBPROCESS (PROC_INST_ID_);
CREATE INDEX IF NOT EXISTS IDX_HI_AGENT_SUB_REMOVAL   ON ACT_HI_AGENT_SUBPROCESS (REMOVAL_TIME_);

CREATE TABLE IF NOT EXISTS ACT_HI_AGENT_STEP (
    ID_                      VARCHAR(64)   NOT NULL,
    SUBPROCESS_EXECUTION_ID_ VARCHAR(64)   NOT NULL,
    PROC_INST_ID_            VARCHAR(64)   NOT NULL,
    EVENT_TYPE_              VARCHAR(64)   NOT NULL,
    SEQUENCE_COUNTER_        BIGINT        NOT NULL DEFAULT 0,
    TIMESTAMP_               TIMESTAMP     NOT NULL,
    LOOP_INDEX_              INT,
    TOOL_CALL_ID_            VARCHAR(255),
    TOOL_NAME_               VARCHAR(255),
    TOOL_ELEMENT_ID_         VARCHAR(255),
    PROMPT_TOKENS_           BIGINT,
    COMPLETION_TOKENS_       BIGINT,
    RESPONSE_TYPE_           VARCHAR(16),
    TOOL_CALL_COUNT_         INT,
    PROMPT_MESSAGES_         CLOB,
    RESPONSE_CONTENT_        CLOB,
    DURATION_MS_             BIGINT,
    STATUS_                  VARCHAR(16),
    ERROR_MESSAGE_           CLOB,
    TOOL_INPUT_              CLOB,
    TOOL_OUTPUT_             CLOB,
    REMOVAL_TIME_            TIMESTAMP,
    PRIMARY KEY (ID_)
);

CREATE INDEX IF NOT EXISTS IDX_HI_AGENT_STEP_SUB_EXEC  ON ACT_HI_AGENT_STEP (SUBPROCESS_EXECUTION_ID_);
CREATE INDEX IF NOT EXISTS IDX_HI_AGENT_STEP_PROC_INST ON ACT_HI_AGENT_STEP (PROC_INST_ID_);
CREATE INDEX IF NOT EXISTS IDX_HI_AGENT_STEP_REMOVAL   ON ACT_HI_AGENT_STEP (REMOVAL_TIME_);
